### PR TITLE
Adjusting the Azure download URL parsing to fix invalid URL error

### LINKED ISSUE #85: Error Expected download URL for Azure IP ranges to start with HTTP but it does not
For the last 2 days scheduled task failed to download Azure IP ranges. Getting this error:

> Scheduler: Error Expected download URL for Azure IP ranges to start with HTTP but it does not. It is: ttps://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20230116..json for task 'Piwik\Plugins\TrackingSpamPrevention\Tasks.updateBlockedIpRanges'

It should be trying to download https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20230116.json

It fails now daily.

### PR DESCRIPTION
**Pull request by snake14**
### Description:

This fixes a parsing issue when determining the full Azure download URL.
Fixes: #85 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — APPROVED** [review]

**Review by tsteur — COMMENTED** [review]
@snake14 generally looks good but do we know how/why this regressed since it's been working before that for a very long time? Is there anything else we can/need to change to make sure it won't change back to the previous logic again?

**Comment by AltamashShaikh** [comment]
We are parsing the HTML and trying to download the URL and content of the page can change and can cause this issue, did a google search to find a direct API, but looks like this is the only best way to get the data,

**Comment by tsteur** [comment]
👍  @AltamashShaikh was just wondering why it worked before and now not anymore and if we can make the solution more stable in case they change their HTML again tomorrow back to what is was for example. Not too important maybe, was just checking if we know why it broke.

**Comment by snake14** [comment]
@tsteur I didn't see an exact reason for the change. As Altamash mentioned, it looks like the content periodically changes and we have had to make other adjustments in the past. I'm not really sure if there's a good way to make it less fragile when they change things on us. I added an integration test that will hopefully help alert us better.

**Comment by tsteur** [comment]
Thanks @snake14 👍

**Pull request merged**
